export const REQUEST_RATE = 'REQUEST_RATE';
export const REQUEST_SOLAR = 'REQUEST_SOLAR';
export const CURRENT_ADDRESS_ID = 'CURRENT_ADDRESS_ID';
export const RECEIVE_RATE = 'RECEIVE_RATE';
export const RECEIVE_SOLAR = 'RECEIVE_SOLAR';
